AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance deployed via CodePipeline

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro

  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  VpcId:
    Type: String
    Default: vpc-0b8a9866b134403da

  SubnetId:
    Type: String
    Default: subnet-0f0f914f1878ae8f6

Resources:
  LabSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for lab EC2
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  LabEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref LabSecurityGroup
      Tags:
        - Key: Name
          Value: lab-ec2-pipeline

Outputs:
  InstanceId:
    Value: !Ref LabEC2Instance
    Description: ID da instancia criada

  PublicIp:
    Value: !GetAtt LabEC2Instance.PublicIp
    Description: IP publico da instancia